/** Lookup tables of Lithuanian phrase fixes and formal-to-informal (tu) rewrites. (Split out of ugc-lt-normalize.ts.) */

export const FORMAL_TO_TU: Array<[RegExp, string]> = [
  [/\bjaučiatės\b/giu, 'jauti'],
  [/\bjaučiate\b/giu, 'jauti'],
  [/(?<!\p{L})jaučiat(?!\p{L})/giu, 'jauti'],
  [/\bjums\b/giu, 'tau'],
  [/\bjūsų\b/giu, 'tavo'],
  [/\bJums\b/g, 'Tau'],
  [/\bJūsų\b/g, 'Tavo'],
  [/\bbūtent jums\b/giu, 'būtent tau'],
  [/\bpritaikytą būtent jums\b/giu, 'pritaikytą būtent tau'],
  [/\bPradėkite\b/g, 'Pradėk'],
  [/\bpradėkite\b/g, 'pradėk'],
  [/\bPajuskite\b/g, 'Pajusk'],
  [/\bpajuskite\b/g, 'pajusk'],
  [/\bpajautekite\b/giu, 'pajusk'],
  [/\bPajautekite\b/g, 'Pajusk'],
  // Before the blind galite → gali: „Dovanos galite įsigyti“ would become a false subject
  // („Dovanos gali įsigyti“). The object of these verbs is accusative (reference §3).
  [/(?<!\p{L})dovanos galite (įsigyti|pirkti|nupirkti|rinktis|išsirinkti|supakuoti)(?!\p{L})/giu, 'dovanas gali $1'],
  [/\bgalite\b/giu, 'gali'],
  [/\bGalite\b/g, 'Gali'],
  [/\bturite\b/giu, 'turi'],
  [/\bTurite\b/g, 'Turi'],
  [/\besate\b/giu, 'esi'],
  [/\bEsate\b/g, 'Esi'],
  [/\bbūsite\b/giu, 'būsi'],
  [/\bžinote\b/giu, 'žinai'],
  [/\bŽinote\b/g, 'Žinai'],
  [/\bnorite\b/giu, 'nori'],
  [/\bNorite\b/g, 'Nori'],
  [/\braskite\b/giu, 'rask'],
  [/\bRaskite\b/g, 'Rask'],
  [/\bskaitykite\b/giu, 'skaityk'],
  [/\bSkaitykite\b/g, 'Skaityk'],
  [/\bbandykite\b/giu, 'bandyk'],
  [/\bBandykite\b/g, 'Bandyk'],
  [/\bpamėginkite\b/giu, 'pamėgink'],
  [/\bdarykite\b/giu, 'daryk'],
  [/\bDarykite\b/g, 'Daryk'],
  [/\bPabandykite\b/g, 'Pabandyk'],
  [/\bpabandykite\b/g, 'pabandyk'],
  [/\bUžsiregistruokite\b/g, 'Užsiregistruok'],
  [/\bužsiregistruokite\b/g, 'užsiregistruok'],
  [/\bPasirinkite\b/g, 'Pasirink'],
  [/\bpasirinkite\b/g, 'pasirink'],
  [/\bApsilankykite\b/g, 'Apsilankyk'],
  [/\bapsilankykite\b/g, 'apsilankyk'],
  [/\bprisijunkite\b/giu, 'prisijunk'],
  [/\bnežinote\b/giu, 'nežinai'],
  [/\bNežinote\b/g, 'Nežinai'],
  [/\bpadėkite\b/giu, 'padėk'],
  [/\bužpildykite\b/giu, 'užpildyk'],
  [/\bUžpildykite\b/g, 'Užpildyk'],
  [/\bsuplanuokite\b/giu, 'suplanuok'],
  [/\bišbandykite\b/giu, 'išbandyk'],
  [/\bNustokit\b/g, 'Nustok'],
  [/\bnustokit\b/giu, 'nustok'],
  [/\bPlanuokite\b/g, 'Planuok'],
  [/\bplanuokite\b/giu, 'planuok'],
  [/\bGaiškite\b/g, 'Gaišk'],
  [/\bgaiškite\b/giu, 'gaišk'],
  [/\bMes padedame jums\b/giu, 'Mes padedame tau'],
  [/\bmes padedame jums\b/giu, 'mes padedame tau'],
]

export const PHRASE_FIXES: Array<[RegExp, string]> = [
  [/\bDabar supranti\b/giu, 'Prisimink'],
  [/(^|[.!?…]\s+)Supranti,\s+kad\b/gimu, '$1Prisimink, kad'],
  [/\bGreitais ir patogiais\b/giu, 'Greita ir patogu'],
  [/ką dedamas į savo maistą/giu, 'ką dedi į savo maistą'],
  [/skanus maistas/giu, 'skanų maistą'],
  [/\bmėgauti vasaros skonimis\b/giu, 'mėgautis vasaros skoniais'],
  [/\bMaisto rinkiniai padeda\b/giu, 'Maisto rinkinys padeda'],
  [/\bkaip gali maisto rinkiniai padeda\b/giu, 'kaip maisto rinkinys gali padėti'],
  [/\bprisimenai skonių paletę\b/giu, 'prisimeni pažįstamus skonius'],
  [/\bruošti maistą gali tapti įtomybė\b/giu, 'maisto ruošimas gali tapti našta'],
  [/(?<!\p{L})įtomybė(?!\p{L})/giu, 'našta'],
  [/\bjau ruošiasi rudenys\b/giu, 'dar tęsiasi vasara'],
  [/\bjaučiame\b/giu, 'jauti'],
  [/\bSiekdami\b/g, 'Kai sieki'],
  [/\bsiekdami\b/giu, 'kai sieki'],
  [/\bkai sieki tikslus\b/giu, 'kai sieki tikslų'],
  [/įpratęs\s*\(\s*-\s*usi\s*\)/giu, 'įpratęs'],
  [/Metu laiko keisti/giu, 'Metas keisti'],
  [/metu laiko keisti/giu, 'metas keisti'],
  [/Metu laiko/giu, 'Metas'],
  [/apgaviusius sprendimus/giu, 'apgaulingus sprendimus'],
  [/apgavusius sprendimus/giu, 'apgaulingų pažadų'],
  [/apgaviusius/giu, 'apgaulingus'],
  [/apgavusius/giu, 'apgaulingus'],
  [/apgaudingus/giu, 'apgaulingus'],
  [/malonus bei tvarias\b/giu, 'malonus bei tvarus'],
  [/maloni bei tvarias\b/giu, 'maloni bei tvari'],
  [/malonus bei tvarius\b/giu, 'malonų ir tvarių'],
  [/malonią bei tvarią\b/giu, 'malonią ir tvarią'],
  [/aklavog[eė]/giu, 'chaosas'],
  [/pensoj[aą]/giu, 'pensiją'],
  [/kiekvienas vakar[uų]/giu, 'kiekvienas vakaro'],
  [/virimo planas/giu, 'maisto planas'],
  [/kasdien(is|į) virimas/giu, 'kasdienis maisto ruošimas'],
  [/kasdienis virimas/giu, 'kasdienis maisto ruošimas'],
  [/jaučiasi pavarg[ęe]s/giu, 'pritrūksta jėgų'],
  [/jaučiasi pavargusi/giu, 'pritrūksta jėgų'],
  [/jaučiasi spaudimas/giu, 'tu jauti spaudimą'],
  [/Dabar žinai, kad virimo planas\.?/giu, 'Dabar žinai. Maisto planas veikia'],
  [/Dabar žinai, kad planas/giu, 'Dabar žinai. Planas'],
  [/\batidėji\b/giu, 'atidedi'],
  [/tampa malonumas/giu, 'tampa malonumu'],
  [/šventė artimiausia/giu, 'artėjanti šventė'],
  [/Ar šventė artimiausia\?/giu, 'Ar artėja šventė?'],
  [/jaustis pasiruošęs/giu, 'jaustis pasiruošę'],
  [/įstrigstate/giu, 'įstringi'],
  [/stringate/giu, 'stringi'],
  [/\bĮsiklausykite\b/g, 'Įsiklausyk'],
  [/įsiklausykite/giu, 'įsiklausyk'],
  [/\bIšlaisvinkite\b/g, 'Išlaisvink'],
  [/išlaisvinkite/giu, 'išlaisvink'],
  [/\bAtverkite\b/g, 'Atverk'],
  [/atverkite/giu, 'atverk'],
  // From prior batch screenshots
  [/energijos visai ne\.?/giu, 'energijos visai nėra'],
  [/nusprendus[,\s]+ką gaminsi/giu, 'sprendžiant, ką gaminti'],
  [/Kaskart nusprendus/giu, 'Kaskart sprendžiant'],
  [/pavargęs\/pavargusi/giu, 'kai pritrūksta jėgų'],
  [/pavargęs arba pavargusi/giu, 'kai pritrūksta jėgų'],
  [/atnešti didelę naštą/giu, 'atnešti didelę naudą'],
  [/Tai sukelia viltį, kad viskas greitai baigsis\.?/giu, 'Tai kelia viltį, kad greitai pasijusi lengviau'],
  [/Galbūt esi pasimetęs, bet tai\.?\s*$/giu, 'Galbūt esi pasimetęs, bet tai puiki pradžia'],
  [/\bbet tai\.\s*$/giu, 'bet tai puiki pradžia'],
  // Never inject URL/CTA into body — rewrite to real content
  [/Sužinok daugiau apie savaitės planus\.?/giu, 'Suplanuok savaitę pagal savo ritmą'],
  [/Suplanuok savaitės meniu\.?/giu, 'Sudėliok savaitės meniu be streso'],
  [/Sužinok daugiau\.?/giu, 'Pradėk nuo trumpo testo'],
  // llama3.1 LT word-salad from failed ugc-lt-fast batches
  [/žaidžiami laikui/giu, 'gaišti laiką'],
  [/kuo žaidžiami/giu, 'kuo gaišti'],
  [/(\p{L}+)\s+(turintis|turinti|galintis|galinti)\b/giu, '$1, $2'],
  [/nebebegaja/giu, 'nebegali'],
  [/nebebegali/giu, 'nebegali'],
  [/užsispyti/giu, 'užsispyręs'],
  [/Naujos receptas/giu, 'Naujas receptas'],
  [/nesuvokiamas dienoraščio,?\s*/giu, 'nesuprantamas dienoraštis. '],
  [/Žarnyno draugiška\.?/giu, 'Žarnynui draugiška.'],
  // Vegan protein batch (Aug 2026 screenshots)
  [/Ar jaučiasi vasaros nuovargis\?/giu, 'Ar jauti vasaros nuovargį?'],
  [/jaučiasi vasaros nuovargis/giu, 'jauti vasaros nuovargį'],
  [/Ar jaučiasi\b/giu, 'Ar jauti'],
  // Only the tu-register slip: "žmogus jaučiasi" is correct 3rd person and must stay.
  [
    /(?<!(?:žmogus|jis|ji|jie|jos|mama|tėtis|senelis|močiutė|draugas|draugė|vyras|moteris|paauglys|vaikas|kiekvienas|niekas|šeima|gavėjas)(?:\s+[^\s,.;!?]+){0,3}\s+)\bjaučiasi\b/giu,
    'jauti',
  ],
  [/trūksta reikiamo baltymai/giu, 'trūksta reikiamų baltymų'],
  [/reikiamo baltymai/giu, 'reikiamų baltymų'],
  [/visus reikiamus aminorūgšties/giu, 'visas reikiamas aminorūgštis'],
  [/reikiamus aminorūgšties/giu, 'reikiamas aminorūgštis'],
  [/aminorūgšties\b/giu, 'aminorūgštis'],
  [/sugalvojome vegan baltymai plan[aą]/giu, 'sukūrėme veganiškų baltymų planą'],
  [/vegan baltymai plan[aą]/giu, 'veganiškų baltymų planą'],
  [/Vegan baltymai/g, 'Veganiški baltymai'],
  [/vegan baltymai/giu, 'veganiški baltymai'],
  [/\bsojos gami\b/giu, 'sojos gaminiai'],
  [/sojos gami(?![a-ząčęėįšųūž])/giu, 'sojos gaminiai'],
  // Cycling / nutrition batch (Aug 2026)
  [/\bmaistinu\b/giu, 'maitinimu'],
  [/režimu ir maistinu/giu, 'režimu ir maitinimu'],
  [/angidrat[uųaą]/giu, 'angliavandenių'],
  [/lengvų angliavandenių/giu, 'lengvų angliavandenių'],
  [/o vaisiai\.\s*Papildomai įkrauti jėgas\.?/giu, 'o vaisiai papildomai įkrauna jėgas'],
  [/o vaisiai\.\s*Papildomai įkrauti\.?/giu, 'o vaisiai papildomai įkrauna energiją'],
  [/Papildomai įkrauti jėgas\.?/giu, 'Papildomai įkrauk jėgas vaisiais'],
  [/Papildomai įkrauti\.?/giu, 'Papildomai įkrauk energiją vaisiais'],
  [/įkrauna energiją jėgas/giu, 'įkrauna jėgas'],
  [/Dažnas pamiršta/giu, 'Dažnai pamiršti'],
  [/Pradėk 5 min\.(?!\s*test)/giu, ''],
  [/Pradėk 5 min\.\s*testą([!\s?.]*🤩*)+/giu, ''],
  [/pradėk 5 min\.\s*testą([!\s?.]*🤩*)+/giu, ''],
  [/tavoknyga\.com\s*[—–-]\s*pradėk testą\.?/giu, ''],
  [/\batstatymo\b/giu, 'atsistatymo'],
  // Weight / mood batch (Aug 2026)
  [/įsismuov[eė]/giu, 'šoka'],
  [/svarstyklės irgi įsismuov[eė]/giu, 'svarstyklės irgi šoka'],
  [/greito atsvarumo/giu, 'greito nusiraminimo'],
  [/\batsvarumo\b/giu, 'nusiraminimo'],
  [/Štai kodėl koncentruotis į vieną skaitmenį\.?\s*Tai mažina/giu, 'Štai kodėl neverta koncentruotis į vieną skaitmenį. Tai mažina'],
  [/Štai kodėl koncentruotis į vieną skaitmenį\.?/giu, 'Štai kodėl neverta koncentruotis į vieną skaitmenį'],
  // Stress / emotional eating (Aug 2026)
  [/nesusimastyk/giu, 'nesusimąstant'],
  [/nesusimastant/giu, 'nesusimąstant'],
  [/maitina tavęs/giu, 'maitina tave'],
  [/ar tai maitina tavęs/giu, 'ar tai maitina tave'],
  [/pasiduoti saldumams/giu, 'pasiduoti saldumynams'],
  [/trumpalaikės palaimos/giu, 'trumpalaikio malonumo'],
  [/siekiant trumpalaikės palaimos/giu, 'siekiant trumpalaikio malonumo'],
  // Proactive nutrition / LT grammar (common OpenEuroLLM slips)
  [/baltimų/giu, 'baltymų'],
  [/biebalu/giu, 'riebalų'],
  [/riebalu(?![a-ząčęėįšųūž])/giu, 'riebalų'],
  [/kalorijus/giu, 'kalorijų'],
  [/kalorijas\b/giu, 'kalorijas'],
  [/anglevanden/giu, 'angliavanden'],
  [/angliavadenių/giu, 'angliavandenių'],
  [/angliavandeniu\b/giu, 'angliavandenių'],
  // Do NOT use /hidratac[iį]/ — it turns correct „hidratacijos" into junk
  [/hidratacijąjos/giu, 'hidratacijos'],
  [/hidratacijąj\w*/giu, 'hidratacijos'],
  [/\bhidrataci\b/giu, 'hidratacija'],
  [/hydratac/giu, 'hidratac'],
  [/subalansota\b/giu, 'subalansuota'],
  [/subalansot[aą]\b/giu, 'subalansuotą'],
  [/organizmas reikia/giu, 'organizmui reikia'],
  [/kūnui reikia degalų/giu, 'kūnui reikia energijos'],
  [/trūksta energija\b/giu, 'trūksta energijos'],
  [/trūksta jėga\b/giu, 'trūksta jėgų'],
  [/daugiau energija\b/giu, 'daugiau energijos'],
  [/sveikos mitybos planas veikia gerai gerai/giu, 'sveikos mitybos planas veikia'],
  [/\bmeal prep\b/giu, 'maisto ruošimas'],
  [/po workout/giu, 'po treniruotės'],
  [/\bworkout\b/giu, 'treniruotė'],
  [/po treniruotė(?![a-ząčęėįšųūž])/giu, 'po treniruotės'],
  [/\bprotein shake\b/giu, 'baltymų kokteilis'],
  [/\bmacros\b/giu, 'makroelementai'],
  [/\btracking\b/giu, 'sekti'],
  [/link in bio/giu, 'tavoknyga.com'],
  [/swipe up/giu, ''],
  [/prisijunk prie bendruomenės/giu, ''],
  [/sek mus/giu, ''],
  [/neužtenk\b/giu, 'neužtenka'],
  [/nebeužtenk\b/giu, 'nebeužtenka'],
  [/pasiruošęs\/pasiruošusi/giu, 'pasiruošęs'],
  [/alkanas\/alkana/giu, 'alkanas'],
  [/pavargęs ir pavargusi/giu, 'kai pritrūksta jėgų'],
  [/tu tu\b/giu, 'tu'],
  [/kad kad\b/giu, 'kad'],
  [/ir ir\b/giu, 'ir'],
  [/planas planas/giu, 'planas'],
  [/maisto maisto/giu, 'maisto'],
  [/sveikatos kelionę su tavoknyga/giu, 'sveikatos kryptį su „Tavo knyga“'],
  [/reikia atsistatymo, o ne tik degalų/giu, 'reikia atsistatymo, o ne tik „degalų“'],
  [/staigius jėgų kritimus/giu, 'staigų jėgų kritimą'],
  [/teikia malonumą, bet energijos visai nėra\?/giu, 'teikia malonumą, bet energijos visai nėra.'],
  // Broken structure / invented “clever” words
  [/Lengvų angliavandenių ir baltymų\.?/giu, 'Rinkis lengvus angliavandenius ir baltymus'],
  [/emocinio kalnelio/giu, 'emocijų kalnelio'],
  [/svytuoti/giu, 'svyruoti'],
  [/svytuoj/giu, 'svyruoj'],
  [/koncentruotis į vieną skaičių/giu, 'neverta koncentruotis į vieną skaičių'],
  [/Štai kodėl\s+(?!neverta\b)([a-ząčęėįšųūž]+oti(?:s)?)\b/giu, 'Štai kodėl neverta $1'],
  [/atgauti kontrolę ir ramumą/giu, 'atgauti kontrolę ir ramybę'],
  [/\bramumą\b/giu, 'ramybę'],
  // Food-waste / planning batch (Aug 2026)
  [/greitai subręsta/giu, 'greitai genda'],
  [/subręsta/giu, 'genda'],
  [/dažnas jauti varginamas/giu, 'dažnai jauti nuovargį'],
  [/jauti varginamas/giu, 'jauti nuovargį'],
  [/\bvarginamas\b/giu, 'išsekęs'],
  [/rūpestų/giu, 'rūpesčių'],
  [/nešlamžtų/giu, 'nesugestų'],
  [/nešlamž/giu, 'nesugest'],
  [/Planuoti kasdien\.\s*Nėra lengva/giu, 'Planuoti kasdien nėra lengva'],
  [/Mes atskiriasi/giu, 'Mes skiriamės'],
  [/atskiriasi nuo/giu, 'skiriasi nuo'],
  [/atskiriasi/giu, 'skiriasi'],
  [/apgavusius sprendimus/giu, 'apgaulingų pažadų'],
  [/užmiršti ką nors panaudoti/giu, 'pamiršti ką nors panaudoti'],
  [/\bužmiršti\b/giu, 'pamiršti'],
  [/\bužmiršai\b/giu, 'pamiršai'],
  [/Įprastas reikalas\.?/giu, 'Pažįstama situacija'],
  [/tiesiog greitai genda/giu, 'greitai genda'],
  [/maisto atliekos tiesiog didina/giu, 'maisto atliekos didina'],
  [/Planuoti kasdien nėra lengva užduotis\.?/giu, 'Planuoti kasdien nėra lengva'],
  [/Dėl to dažnas /giu, 'Dėl to dažnai '],
  [/\bdažnas jauti\b/giu, 'dažnai jauti'],
  [/\bDažnas jauti\b/g, 'Dažnai jauti'],
  [/maistinimas/giu, 'maitinimas'],
  [/maistinimu/giu, 'maitinimu'],
  [/reikiamo baltymų/giu, 'reikiamų baltymų'],
  [/reikiamų baltymai/giu, 'reikiamų baltymų'],
  [/gerai gerai/giu, 'gerai'],
  [/labai labai/giu, 'labai'],
  [/visai visai/giu, 'visai'],
  [/kasdien\.\s*Nėra /giu, 'kasdien nėra '],
  [/Mes skiriamės nuo trumpalaikių planų, kurie skamba kaip greiti sprendimai/giu, 'Mes skiriamės nuo trumpalaikių planų ir greitų pažadų'],
  // Live model / meta.json Aug 2026 — we-forms, gender, invented words
  [/\bpastebėjau\b/giu, 'pastebėjai'],
  [/\bsusiduriame\b/giu, 'susiduri'],
  [/\bišmetame\b/giu, 'išmeti'],
  [/\bperkame\b/giu, 'perki'],
  [/\bneturime\b/giu, 'neturi'],
  [/\bneplanuojame\b/giu, 'neplanuoji'],
  [/\bsuvartojame\b/giu, 'suvartoji'],
  [/\bmanome\b/giu, 'manai'],
  [/\bDažnas nori\b/g, 'Dažnai nori'],
  [/\bdažnas nori\b/giu, 'dažnai nori'],
  [/fokusuoja į/giu, 'kreipia dėmesį į'],
  [/\bfokusuoja\b/giu, 'kreipia dėmesį'],
  [/Kaip Tai Poveikio/giu, 'Kaip tai veikia'],
  [/kaip tai poveikio/giu, 'kaip tai veikia'],
  [/poveikio tavo/giu, 'veikia tavo'],
  [/\batsižvelgdamas\b/giu, 'atsižvelgiant'],
  [/\batsižvelgdama\b/giu, 'atsižvelgiant'],
  [/Tavo savijauta\.\s*Tavo prioritetas/giu, 'Tavo savijauta — tavo prioritetas'],
  [/jaustis pasiruošusi/giu, 'jaustis pasiruošę'],
  [/\bbadmečio\b/giu, 'alkio'],
  [/\btreniruoje\b/giu, 'treniruotėje'],
  [/\bpabandinti\b/giu, 'išbandyti'],
  [/\bskaidrutes\b/giu, 'skaidres'],
  [/\bpatiekas\b/giu, 'patiekalas'],
  [/\brudenių\b/giu, 'rudens'],
  [/rudenių/giu, 'rudens'],
  [/hidratacijąjąjos/giu, 'hidratacijos'],
  [/hidratacijąjąj\w*/giu, 'hidratacijos'],
  [/Štai kodėl sugalvojome/giu, 'Štai kodėl sukūrėme'],
  [/\bVegan\b(?!\s*baltymai)/g, 'Veganiškas'],
  [/Crossfit'?o?\b/giu, 'intensyvios treniruotės'],
  [/Tavo skoniui pritaikytą ir lengvai įgyvendinamą\.?/giu, 'Planas pritaikytas tavo skoniui ir lengvai įgyvendinamas'],
  [/\besi\b([^.!?]{0,40})\balkis\b/giu, 'esi$1alkanas'],
  [/tampa malonumas, o ne įsipareigojimu/giu, 'tampa malonumu, o ne įsipareigojimu'],
  [/energijos eikvojimo be reikalo/giu, 'energijos eikvojimą be reikalo'],
  [/vandens eikvojimo be reikalo/giu, 'vandens eikvojimą be reikalo'],
  [/pinigų eikvojimas/giu, 'pinigų švaistymas'],
  [/aplinkosauginės problemos dalis/giu, 'aplinkos problema'],
  [/Pradėk Šiandien!?/giu, 'Pradėk šiandien'],
  [/Svorio Tikslai/g, 'Svorio tikslai'],
  [/Maisto Švaistymas/g, 'Maisto švaistymas'],
  // Batch_2026-08-05_232736 — tu/mes shift, participle agreement, wrong reflexive
  [/Ką dedame į/giu, 'Ką dedi į'],
  [/\bdedame\b/giu, 'dedi'],
  [/\bvalgome\b/giu, 'valgai'],
  [/\bruošiame\b/giu, 'ruoši'],
  [/\bperkame į\b/giu, 'perki į'],
  [/suverstų daržovių kalną/giu, 'suverstą daržovių kalną'],
  [/suverstų\s+(\w+)\s+kalną/giu, 'suverstą $1 kalną'],
  [/\bPasiskirstyk\b/g, 'Paskirstyk'],
  [/\bpasiskirstyk\b/giu, 'paskirstyk'],
  [/paskirstyk daržoves savaitgaliams/giu, 'paskirstyk daržoves savaitei'],
  [/daržoves savaitgaliams/giu, 'daržoves savaitei'],
  [/Pasiskirstyk daržoves savaitgaliams/giu, 'Paskirstyk daržoves savaitei'],
  // Audit post-01..10 (Aug 2026 fortress A–Z)
  [/\bpatiekalimis\b/giu, 'patiekalais'],
  [/Jaučiuosi varginantis/giu, 'Jauti nuovargį'],
  [/jaučiuosi varginantis/giu, 'jauti nuovargį'],
  [/\baš ruošiasi\b/giu, 'ruošiesi'],
  [/su aišku savaitės mitybos planas/giu, 'su aiškiu savaitės mitybos planu'],
  [/leidžia kepenims atpalaiduoti/giu, 'leidžia kepenims lengviau dirbti'],
  [/\btrūgsta\b/giu, 'trūksta'],
  [/\bbesimauginantis\b/giu, 'besimaitinantis'],
  [/jauti vasaros karštis/giu, 'jauti vasaros karštį'],
  // \b fails before LT diacritics (į/ū/…) — use lookaround
  [/(?<!\p{L})įtūmiu(?!\p{L})/giu, 'įtemptu'],
  [/\bnorėtumis\b/giu, 'norėtum'],
  [/\brežinas\b/giu, 'režimas'],
  [/Jausi ramesnis/giu, 'Jausiesi ramiau'],
  [/jausi ramesnis/giu, 'jausiesi ramiau'],
  [/\bsunksta\b/giu, 'sunkėja'],
  [/\bnuovokio\b/giu, 'nuovargio'],
  [/\bAišus\b/g, 'Aiškus'],
  [/\baišus\b/giu, 'aiškus'],
  [/Insulinrezistencija/giu, 'insulino rezistencija'],
  [/(?<!\p{L})medžiukų(?!\p{L})/giu, 'medžiagų'],
  [/\btebetruksminga\b/giu, 'vis dar trukdo'],
  [/dar vis dar trukdanti/giu, 'vis dar trukdo'],
  [/vis dar trukdanti/giu, 'vis dar trukdo'],
  [/\brandu\b/giu, 'randi'],
  [/daryti įtakos/giu, 'daryti įtaką'],
  [/rezultatai vis nepastovi/giu, 'rezultatai vis nepastovūs'],
  [/išleidžiamos pinigai/giu, 'išleidžiami pinigai'],
  [/\bStengiame\b/g, 'Stengiesi'],
  [/\bstengiame\b/giu, 'stengiesi'],
  [/anglies hidrat[uų]/giu, 'angliavandenių'],
  [/atsiliepia savijauta(?![iį])/giu, 'atsiliepia savijautai'],
  [/jaustis gyvesnis ir produktyvus/giu, 'jaustis energingesniam'],
  [/jaustis sotus, o ne badaujantis/giu, 'jaustis sotiems, o ne alkaniems'],
  [/jaustis lengvas/giu, 'jaustis lengviau'],
  [/jau ruošiasi atvykti ramybė/giu, 'jau artėja ramybė'],
  [/apgailėtinas miegas/giu, 'prastas miegas'],
  [/\bpasiūlysime\b/giu, 'gali pasiūlyti'],
  [/Mes pritaikome/giu, 'Tu pritaikai'],
  [/\bpritaikome\b/giu, 'pritaikai'],
  [/\bruošiamės\b/giu, 'ruošiesi'],
  [/(?<!\p{L})užsisklendiname(?!\p{L})/giu, 'užsisklendi'],
  [/\bpamirštame\b/giu, 'pamiršti'],
  [/Galime eksperimentuoti/giu, 'Gali eksperimentuoti'],
  [/\bpasiektume\b/giu, 'pasiektum'],
  [/Kiekvienas iš mūsų susiduria/giu, 'Dažnai susiduri'],
  [/Kiekvienas iš mūsų/giu, 'Dažnai'],
  [/\bJaučiuosi\b/g, 'Jauti'],
  [/\bjaučiuosi\b/giu, 'jauti'],
  [/kai esi įstrigusi/giu, 'kai stringi'],
  [/kai esi įstrigęs/giu, 'kai stringi'],
  [/(?<!\p{L})įstrigusi(?!\p{L})/giu, 'įstrigęs'],
  [/\bbesiruošdama\b/giu, 'besiruošdamas'],
  [/kai ruošdamasis\b/giu, 'kai ruošiesi'],
  [/\bkontroliuodama\b/giu, 'kai kontroliuoji'],
  [/Ramesnis, o ne uždusiantis\.?/giu, 'Jausiesi ramiau, o ne uždusęs.'],
  [/Pasirūpink savimi\.(\s*Kiekvieną dieną\.)?/giu, 'Pasirūpink savimi kiekvieną dieną.'],
  [/kiekvieną dieną\.\s*kiekvieną dieną\./giu, 'Kiekvieną dieną.'],
  // Vision batch-5 (Aug 2026) — post-03/05 shipped inventeds + person/gender
  [/(?<!\p{L})kątį(?!\p{L})/giu, 'kątik'],
  [/(?<!\p{L})rutinoją(?!\p{L})/giu, 'rutiną'],
  [/(?<!\p{L})rutinoj(?!\p{L})a?/giu, 'rutiną'],
  [/(?<!\p{L})bėdeles(?!\p{L})/giu, 'bėrimus'],
  [/(?<!\p{L})bėdel(?!\p{L})\w*/giu, 'bėrimus'],
  [/(?<!\p{L})valgoji(?!\p{L})/giu, 'valgai'],
  [/(?<!\p{L})vargstį(?!\p{L})/giu, 'vargą'],
  [/(?<!\p{L})viršinamas(?!\p{L})/giu, 'virškinamas'],
  [/tebesildo/giu, 'šildo'],
  [/\bTu\s+pats\(i\)\b/giu, 'Tu'],
  [/Tu tapsi savo kūno eksperimentų vadovas/giu, 'Tu tapsi savo kūno eksperimentų vadovu'],
  [/eksperimentų vadovas/giu, 'eksperimentų vadovu'],
  [/pats\(i\)/giu, 'tu'],
  [/pati\(s\)/giu, 'tu'],
  [/\bTu\s+tu\b/giu, 'Tu'],
  [/\bGalėčiau\b/g, 'Galėtum'],
  [/\bgalėčiau\b/giu, 'galėtum'],
  [/\bPradėjau\b/g, 'Pradėjai'],
  [/\bpradėjau\b/giu, 'pradėjai'],
  [/\baš planuoju\b/giu, 'tu planuoji'],
  [/Štai kodėl aš planuoju/giu, 'Štai kodėl planuoji'],
  [/\bStebėdama\b/g, 'Kai stebi'],
  [/\bstebėdama\b/giu, 'kai stebi'],
  [/Taigi,\s*suplanavimas\.?/giu, 'Taigi svarbu iš anksto suplanuoti.'],
  [/\bsuplanavimas\.\s*$/giu, 'suplanuok iš anksto.'],
  [/keliose skirtinguose patiekaluose/giu, 'keliuose skirtinguose patiekaluose'],
  [/pajusti energijos/giu, 'pajustum energiją'],
  [/\bnesportuojame\b/giu, 'nesportuoji'],
  // Vision batch 8 (Aug 2026) — person/register and malformed LT
  [/(?<!\p{L})galimi(?!\p{L})/giu, 'gali'],
  [/(?<!\p{L})noriu(?!\p{L})/giu, 'nori'],
  [/(?<!\p{L})suprantu(?!\p{L})/giu, 'supranti'],
  [/(?<!\p{L})įsitikinau(?!\p{L})/giu, 'įsitikinai'],
  [/(?<!\p{L})patenkinčiau(?!\p{L})/giu, 'patenkintum'],
  [/Tavęs apjungia/giu, 'Tave užgriūva'],
  [/(?<!\p{L})apjungia(?!\p{L})/giu, 'sujungia'],
  [/nuo kasmens(?!\p{L})/giu, 'nuo maisto švaistymo'],
  [/maisto gėriu/giu, 'maisto skoniu'],
  [/kasdieninis balansavimas/giu, 'kasdienį balansą'],
  [/nėra pats geriausias/giu, 'nėra geriausias'],
  [/Tai nėra pats geriausias/giu, 'Tai nėra geriausias'],
  [/Ar meal kit\b/giu, 'Ar maisto rinkinys'],
  [/\bmeal kit\b/giu, 'maisto rinkinys'],
  [/Rugsėjis artimas, o tau/giu, 'Ar rugsėjį planuoji ramiau?'],
  [/(?<!\p{L})šventvėlių(?!\p{L})/giu, 'švenčių'],
  [/gali suderinsi/giu, 'gali suderinti'],
  [/Prieš tai tu skyręs\(-ei\) savaitę tik planuodamas\(-a\) renginius\.?/giu, 'Anksčiau visą savaitę planavai renginius.'],
  [/Ankstesnėmis metais tu jaučiausi išsekęs\(-us\) po kiekvienos didelės šventės\.?/giu, 'Ankstesniais metais po kiekvienos didelės šventės tau pritrūkdavo jėgų.'],
  [/(?<!\p{L})utėlius(?!\p{L})/giu, 'mažylis'],
  [/suaugusiųjų valgymo ramybė nepažeidžiama/giu, 'suaugusiųjų valgymas lieka ramus'],
  [/(?<!\p{L})Ištvermas(?!\p{L})/gu, 'Ištvermė'],
  [/(?<!\p{L})ištvermas(?!\p{L})/giu, 'ištvermė'],
  [/praleidi dienos ritmą ir jausiesi pavargęs/giu, 'prarandi dienos ritmą ir jautiesi pavargęs'],
  [/įsisisteminus pastovų valgiarastį/giu, 'kai turi pastovų valgiaraštį'],
  [/(?<!\p{L})viršvalgėjimo(?!\p{L})/giu, 'persivalgymo'],
  [/(?<!\p{L})įsisotinęs(?!\p{L})\s+miegas/giu, 'kokybiškas miegas'],
  [/(?<!\p{L})Pamėteli(?!\p{L})/gu, 'Pastebi'],
  [/(?<!\p{L})pamėteli(?!\p{L})/giu, 'pastebi'],
  [/Šaldytuvo durys atsiranda/giu, 'Šaldytuve atsiranda'],
  [/pajausi tikrą pokyčio įtaką/giu, 'pajusi tikrą pokytį'],
  [/(?<!\p{L})užkasti(?!\p{L})/giu, 'užkąsti'],
  [/Dabar atsiranda daug nusivylimo dėl vasaros pabaigos\.?/giu, 'Vasaros pabaiga gali nuvilti.'],
  // Aug-7 PM batch (5 posts) — grammar, logic, register
  [/\bNenorisi\b/giu, 'Nenori'],
  [/\bnenorisi\b/giu, 'nenori'],
  [/(?<!\p{L})pasirūpintį(?!\p{L})/giu, 'pasirūpinti'],
  [/\bima dėvėti\b/giu, 'ima gesti'],
  [/\bAr vakarienė\.\s*Kasdienis stresas\?/giu, 'Ar vakarienė — kasdienis stresas?'],
  [/\bkontrolę virš savo dienos\b/giu, 'kontrolę savo dienoje'],
  [/\bkauptis pradeda nereikalingas atsargos\b/giu, 'kaupiasi nereikalingos atsargos'],
  [/\bDažnai įsidedami produktus\b/giu, 'Dažnai per daug produktų įsidedi'],
  [/\bpamiršti jų panaudojimo datą\b/giu, 'pamirši jų galiojimo datą'],
  [/\bpamiršti ką turėji\b/giu, 'pamirši, ką turėjai'],
  [/\bSupranti, kad tvarkinga virtuvė\.?\s*$/giu, 'Supranti, kad tvarkinga virtuvė sutaupo laiko.'],
  [/\bNorėjau maisto rinkinio\b/giu, 'Norėjai maisto rinkinio'],
  [/\bAtsisakiau prabangos\b/giu, 'Atsisakei prabangos'],
  [/\bSuplanavus savaitės meniu taupysi\b/giu, 'Kai suplanuoji savaitės meniu, taupysi'],
  [/\bPlanuodamas vaisių pirkinius\b/giu, 'Kai planuoji vaisių pirkinius'],
  [/\bplanuodamas kasdienį meniu\b/giu, 'planuojant kasdienį meniu'],
  [/\bvisada tuščias tik tada, kai reikia naujų\b/giu, 'tuščias tik tada, kai laikas papildyti'],
  [/\bnes galvoji\.\s*Kada nors prisimsi\b/giu, 'nes galvoji, kad prisiminsi vėliau'],
  [/\bDžiaugsmas kyla nuo sąmoningesnio vartojimo\b/giu, 'Mažiau maisto eina į šiukšlynę'],
  [/\batidaugi\b/giu, 'atidarai'],
  [/\bpirkiams\b/giu, 'pirkimams'],
  [/\bdalybams\b/giu, 'dalykams'],
  [/\bpirmiami\b/giu, 'perkami'],
  [/\bsubyrauja\b/giu, 'genda'],
  [/\bišmetini\b/giu, 'išmeti'],
  [/\bgeros būklės maisto\b/giu, 'geros būklės maistą'],
  [/\bjei persigalvoji\b/giu, 'kai pakeiti įpročius'],
  [/\blikę daržovės\b/giu, 'likusios daržovės'],
  [/\breikalingo kiekio produktus\b/giu, 'reikiamą kiekį produktų'],
  [/\bpasijausti atsakingas\b/giu, 'pasijausti atsakingu'],
  [/\bpamiršti apie ją\b/giu, 'pamirši apie jį'],
  [/\bKada nors prisimsi\b/giu, 'kad prisiminsi vėliau'],
  [/\bprisimsi\b/giu, 'prisiminsi'],
  [/\bSuplanuotas pirkinių planas\b/giu, 'Pirkinių planas'],
  [/\bpadeda maistui pasibaigti laiku\b/giu, 'padeda panaudoti maistą laiku'],
  [/\bsugadina tavo laiką\b/giu, 'švaisto tavo laiką'],
  [/\bmėgstamam pomėgiui\b/giu, 'pomėgiui'],
  [/\bgalimybę atsipalaidavimui\b/giu, 'galimybę atsipalaiduoti'],
  [/\berdvės atsipalaidavimui ir atkurti\b/giu, 'erdvės atsipalaiduoti ir atkurti'],
  [/\btiesiog atsipalaidavimui\b/giu, 'tiesiog atsipalaiduoti'],
  [/\boptimalų sunaudojimą\b/giu, 'visą kiekį laiku'],
  [/\bnetiesiogiai atidedi\b/giu, 'atidedi'],
  [/\bTu norėtum pasirūpintį\b/giu, 'Norėtum pasirūpinti'],
  [/\bnorėtum pasirūpintį\b/giu, 'norėtum pasirūpinti'],
  [/\bAsmeninis planas pritaiko pasirinkimus prie tavo kasdienio ritmo\b/giu, 'Aiškus planas sumažina kasdienių sprendimų skaičių'],
  [/\bTodėl lengviau nuosekliai judėti pasirinkta kryptimi\b/giu, 'Todėl lengviau laikytis savo ritmo'],
  [/\bKasdien renkiesi ramiau\b/giu, 'Kasdien maistą renkiesi ramiau'],
  [/\bAiškus asmeninis planas padeda kasdien rinktis ramiau\b/giu, 'Aiškus planas padeda kasdien maistą rinktis ramiau'],
  [/\bvisada tuščias tik tada\b/giu, 'tuščias tik tada'],
  [/\bDažnas impulsyvus\b/giu, 'Dažnai impulsyviai'],
  [/\bNėra aiškios strategijos pirkiams\b/giu, 'Nėra aiškios pirkinių strategijos'],
  // Aug-7 PM screenshots batch 2 — idioms, season filler, grammar
  [/\btarsi ratuose\b/giu, 'ratų rate'],
  [/\bsavaitės vis atsinaujina\b/giu, 'savaitė vėl prasideda nuo nulio'],
  [/\bSiekdami tikslus dažnai susiduri\b/giu, 'Kai sieki tikslų, dažnai susiduri'],
  [/\bsavaitės pageidavimų\b/giu, 'savaitės ritmo'],
  [/\bbei mėgautiesi\b/giu, 'ir mėgaukis'],
  [/\bmintys apie maisto gaminimą atstumia\b/giu, 'nenori galvoti apie maisto gaminimą'],
  [/\bsveikatą tausojančius pietus\b/giu, 'sveikus pietus'],
  [/\beina viena koja\b/giu, 'eina koja kojon'],
  [/\breikia stiprios energijos atsargas papildyti\b/giu, 'reikia papildyti energijos atsargas'],
  [/\bsotumo užtikrinančio\b/giu, 'sotumą užtikrinančio'],
  [/\bmaitintis sveikais ir skaniai\b/giu, 'maitintis sveikai ir skaniai'],
  [/\benergija nepristigs\b/giu, 'energijos nepristigs'],
  [/\bAr prisimeni pirmą kartą užsisakiau\b/giu, 'Ar prisimeni, kai pirmą kartą užsisakei'],
  [/\bnėra visada lengva\b/giu, 'ne visada lengva'],
  [/\bTu gali norėti\b/giu, 'Norisi'],
  [/\brasti patinkančius produktus ir įpročius\b/giu, 'rasti patinkančius produktus'],
  [/(?<!\p{L})užsiemyje(?!\p{L})/giu, 'užsienyje'],
  [/\bprisimena skonių paletę\b/giu, 'prisiminti skonių paletę'],
  [/\bprisimena skonių\b/giu, 'prisiminti skonius'],
  [/\bišseka jėgas\b/giu, 'išsekina jėgas'],
  [/\bjaučiat\b/giu, 'jauti'],
  [/\bviskas atsinaujina\b/giu, 'viskas vėl keičiasi'],
  [/\borganizacijos ir paruošimo\b/giu, 'planavimo'],
  [/\bPo sunkaus rugpjūčio karščio[^,]*,\s*/giu, ''],
  [/\bRugpjūčio karštį jaučiame iki galo,\s*o\s*/giu, ''],
  [/\bRugpjūčio karštis dar juntamas, tačiau\s*/giu, ''],
  [/\bRugpjūčio karštis dar primena vasarą, bet\s*/giu, ''],
  [/\bRugpjūčio karštis palieka tave išsekusį,\s*o\s*/giu, ''],
  [/\bAr jaučiat rugpjūčio karštį\?/giu, 'Ar po treniruotės jauti nuovargį?'],
  [/\bŠis savaitgalis primena paskutines vasaros dienas, o tu\b/giu, 'Tu'],
  // Aug-7 night batch — captions + slides
  [/\bbet ne nori\b/giu, 'bet nenori'],
  [/\bne nori jausti\b/giu, 'nenori jausti'],
  [/\bpilno energijos\b/giu, 'pilnai energijos'],
  [/\brandamų baltymai\b/giu, 'randamų baltymų'],
  [/\bkaltės kamuojamas jausmas\b/giu, 'kaltės kamuojamą jausmą'],
  [/\bsusisprendimo\b/giu, 'susigrupavimo'],
  [/\bkontrolę virš savo kūno\b/giu, 'savo kūno kontrolę'],
  [/\bDažnai tu jauti\b/giu, 'Dažnai jauti'],
  [/\bšoka aukštyn ir žemyn\b/giu, 'svyruoja'],
  // Allergy / ingredient batch
  [/\btavo mėgstamiausiu maisto rinkiniu\b/giu, 'tavo mėgstamiausiame maisto rinkinyje'],
  [/\bmėgstamiausiu maisto rinkiniu\b/giu, 'mėgstamiausiame maisto rinkinyje'],
  [/\bJauti neįprastas diskomfortas\b/giu, 'Jauti neįprastą diskomfortą'],
  [/\bjauti neįprastas diskomfortas\b/giu, 'jauti neįprastą diskomfortą'],
  [/\batskirti saugy nuo rizikos\b/giu, 'atskirti saugų nuo rizikingo'],
  [/(?<!\p{L})saugy(?!\p{L})/giu, 'saugų'],
  [/\bPrieš ateinančius patiekalus pasitikėk savimi\b/giu, 'Rinkdamas patiekalus, pasitikėk savimi'],
  // Aug-7 23:xx batch — logic, invented words, we-forms, instrumental case
  [/\bneapibrūkštumo\b/giu, 'neapibrėžtumo'],
  [/\bneapibrūkštum\w*/giu, 'neapibrėžtumo'],
  [/\bnemalnumai\b/giu, 'nemalonumai'],
  [/\bnemalnum(\w*)/giu, 'nemalonum$1'],
  [/Testas atskleidžia, ką tau telieka norėti\.?/giu, 'Testas atskleidžia, ko tau iš tiesų norisi.'],
  [/\bką tau telieka norėti\b/giu, 'ko tau iš tiesų norisi'],
  [/Prieš tai buvęs spėjimas tampa tikslesnis ir efektyvesnis\.?/giu, 'Vietoje spėliojimo atsiranda aiškus pasirinkimas.'],
  [/\.\s*Ne atsitiktinumas\.?/giu, ', o ne atsitiktinumas.'],
  [/Štai kaip vakarienės pasirinkimas tavo kasdienybėje pasikeis!?\.?/giu, 'Štai kaip pasikeičia tavo vakarienės rutina.'],
  [/(?<!\p{L})žinsi(?!\p{L})/giu, 'žinosi'],
  [/\bžinosi ką užsisakysi\b/giu, 'žinosi, ką užsisakyti'],
  [/\bo piniginė džiaugiasi\b/giu, 'o piniginė džiaugsis'],
  [/Tikina, jog nuoseklumas padės išvengti atgalinio žingsnio\.?/giu, 'Tiki, kad nuoseklumas padės išvengti žingsnio atgal.'],
  [/\bTikina, jog\b/giu, 'Tiki, kad'],
  [/\bišvengti atgalinio žingsnio\b/giu, 'išvengti žingsnio atgal'],
  [/(?<!\p{L})Šeši mėnesius(?!\p{L})/gu, 'Šešis mėnesius'],
  [/Šešis mėnesius tu esi įsitikinęs/giu, 'Šešis mėnesius buvai įsitikinęs'],
  [/\bkaita aplink tave gali būti nepastebima, kol vėluosi reaguoti\b/giu, 'pokyčiai aplink tave lieka nepastebėti, kol vėluoji reaguoti'],
  [/\bkol vėluosi reaguoti\b/giu, 'kol vėluoji reaguoti'],
  [/\bkaita aplink tave\b/giu, 'pokyčiai aplink tave'],
  [/(?<!\p{L})sužinoji(?!\p{L})/giu, 'sužinosi'],
  [/Sužinok apie žarnynui draugiškus ingredientus ir jų naudą\.?/giu, 'Žarnynui draugiški ingredientai gali pastebimai pagerinti savijautą.'],
  [/\btapo iššūkis\b/giu, 'tapo iššūkiu'],
  [/\btampa iššūkis\b/giu, 'tampa iššūkiu'],
  [/\btampa didesnis iššūkis\b/giu, 'tampa didesniu iššūkiu'],
  [/\btaps iššūkis\b/giu, 'taps iššūkiu'],
  [/\bgalvoji ką valgyti\b/giu, 'galvoji, ką valgyti'],
  [/\bima daug jėgų(?!\p{L})/giu, 'atima daug jėgų'],
  [/\batsipalaidavusios savaitės\b/giu, 'ramesnės savaitės'],
  [/\batsipalaiduojančia savaitės eiga\b/giu, 'ramesne savaitės eiga'],
  [/\bsutaupyti energijos ir dėmesio\b/giu, 'sutaupyti energijos ir laiko'],
  [/\bmėgautis skanu bei sveiku pietumi\b/giu, 'mėgautis skaniais ir sveikais pietumis'],
  [/\bskanu bei sveiku pietumi\b/giu, 'skaniais ir sveikais pietumis'],
  [/\bskanu bei sveiku\b/giu, 'skaniu ir sveiku'],
  // Colon titles: interrogative / A-ar-B tails are questions (\b fails on LT letters)
  [/(:\s*(?:kodėl|ką|kaip|kas|kur|kada|kiek|nuo ko)(?!\p{L})[^?!.…]*?)[.!…]*\s*$/gimu, '$1?'],
  [/(:\s*\p{L}+(?:\s+\p{L}+){0,3}\s+ar\s+\p{L}+[^?!.…]*)[.!…]*\s*$/gimu, '$1?'],
  // Generic missing comma before subordinate interrogatives
  [/(?<!\p{L})(žinai|žinosi|supranti|galvoji|pamiršti|sprendi|nežinai|suvoki)\s+(ką|kaip|kodėl|kur|kada)(?!\p{L})/giu, '$1, $2'],
  // Masculine participle hook openers → tu-question
  [/^(Pavargęs)\s+nuo\s+(.+?)[.!…]*\s*$/gimu, 'Pavargai nuo $2?'],
  [/^(Išsekęs)\s+nuo\s+(.+?)[.!…]*\s*$/gimu, 'Išsekai nuo $2?'],
  [/^(Įstrigęs)\s+(.+?)[.!…]*\s*$/gimu, 'Įstrigai $2?'],
  // Aug-8 15:00 batch — systemic + quote repairs
  [/(?<!\p{L})kodėl jis skęsta\?/giu, 'kodėl jis blėsta?'],
  [/(?<!\p{L})valgio vartojimo laikai(?!\p{L})/giu, 'valgymo laikas'],
  [/(?<!\p{L})Suplanuoti valgio laikai(?!\p{L})/giu, 'Suplanuotas valgymo laikas'],
  [/(?<!\p{L})suplanuoti valgio laikai(?!\p{L})/giu, 'suplanuotas valgymo laikas'],
  [/(?<!\p{L})organizmo resursai ištuštėja(?!\p{L})/giu, 'organizmo atsargos senka'],
  [/Ankstesnis posūkis atskleidžia, kad\s*/giu, ''],
  [/(?<!\p{L})su dieną užimančiais darbais(?!\p{L})/giu, 'su dienos darbais'],
  [/(?<!\p{L})vargdas eksperimentavimas(?!\p{L})/giu, 'varginantis eksperimentas'],
  [/(?<!\p{L})vargdas(?!\p{L})/giu, 'varginantis'],
  [/(?<!\p{L})Manėsi veganas būti\.?/giu, 'Manei, kad veganu būti paprasta.'],
  [/(?<!\p{L})nežinomybės paslaptys(?!\p{L})/giu, 'daug nežinomybės'],
  [/(?<!\p{L})Paskui supranti(?!\p{L})/giu, 'Vėliau supranti'],
  [/(?<!\p{L})susidoroti su pirmuoju butu(?!\p{L})/giu, 'susidoroti su pirkiniais naujame būste'],
  [/(?<!\p{L})ilgų virimo seansų(?!\p{L})/giu, 'ilgo gaminimo'],
  [/(?<!\p{L})virimo seans\p{L}*/giu, 'gaminimo'],
  [/(?<!\p{L})Greitas puodas(?!\p{L})/giu, 'Greitas patiekalas'],
  [/(?<!\p{L})greitas puodas(?!\p{L})/giu, 'greitas patiekalas'],
  [/(?<!\p{L})didelę švaistymo apimtį(?!\p{L})/giu, 'daug švaistymo'],
  [/(?<!\p{L})pasirinkdamas paruoštų ingredientų komplektus(?!\p{L})/giu, 'kai renkiesi paruoštus ingredientus'],
  [/(?<!\p{L})susidūrimas su improvizacija baigiasi didesnėmis išlaidomis ir vargais(?!\p{L})/giu, 'improvizacija dažnai baigiasi didesnėmis išlaidomis'],
  [/(?<!\p{L})dažnas susidūrimas su improvizacija baigiasi didesnėmis išlaidomis ir vargais(?!\p{L})/giu, 'improvizacija dažnai baigiasi didesnėmis išlaidomis'],
  [/(?<!\p{L})mėgautiesi(?!\p{L})/giu, 'mėgaujiesi'],
  [/(?<!\p{L})naujiems užduočiams(?!\p{L})/giu, 'naujiems užduotims'],
  [/(?<!\p{L})sudėtinimi(?!\p{L})/giu, 'sudėtimi'],
  // Aug-8 batch — grammar, logic, question register
  [/\btrukdyti tavo kasdienę veiklą ir nuotaiką(?!\p{L})/giu, 'trukdyti tavo kasdienei veiklai ir nuotaikai'],
  [/\btrukdyti tavo kasdienę veiklą(?!\p{L})/giu, 'trukdyti tavo kasdienei veiklai'],
  [/\bpasirenki ką kita\b/giu, 'pasirenki kitką'],
  [/\brenkiesi ką kita\b/giu, 'renkiesi kitką'],
  [/(?<!\p{L})įtikinimo mūšiu(?!\p{L})/giu, 'kasdiene kova'],
  [/(?<!Ar\s)Suplanuoti pietus tampa didesniu iššūkiu nei darbo užduotys[.?]*/gu, 'Ar suplanuoti pietus tampa didesniu iššūkiu nei darbo užduotys?'],
  [/\bgalvoji, ką valgyti\.(?=\s|$)/giu, 'galvoji, ką valgyti?'],
  // Aug-8 batch — register clash, backwards logic, agreement
  [/,\s*ne seną šabloną\s*\.?/giu, '.'],
  [/\bpasiekimai vis lieka tie patys\.(?=\s|$)/giu, 'pasiekimai vis lieka tie patys?'],
  [/\bInvestuok laiko ir dėmesio į(?!\p{L})/giu, 'Investuok laiką ir dėmesį į'],
  [/\binvestuok laiko\b/giu, 'investuok laiką'],
  [/\briboti potencialą ir naujų galimybių įsisavinimą(?!\p{L})/giu, 'riboti potencialą ir naujas galimybes'],
  [/\bstrategijas pasiekiamam augimui\b/giu, 'augimo kryptis'],
  [/\bNaujagimis kelia nereguliarų laiką(?!\p{L})/giu, 'Naujagimio ritmas nereguliarus'],
  [/\bkai vaikas verčia miego neatsisakyti\b/giu, 'kai vaikas neleidžia išsimiegoti'],
  [/\bJauti nuovargis ir noras padėti sau\b/giu, 'Jauti nuovargį ir norą padėti sau'],
  [/\bJauti nuovargis\b/giu, 'Jauti nuovargį'],
  [/\bjauti nuovargis\b/giu, 'jauti nuovargį'],
  [/(?<!\p{L})rūpestėlis(?!\p{L})/giu, 'rūpestis'],
  [/(?<!\p{L})rūpestėl(\w*)/giu, 'rūpest$1'],
  [/\bverta pasitikėti įprastais patarimais ir atradinėti savitą kelią(?!\p{L})/giu, 'verta ne vien pasikliauti įprastais patarimais, bet atrasti savitą kelią'],
  [/\bkodėl nesibaigia sotis\?/giu, 'kodėl sotumas toks trumpas?'],
  [/\bnesibaigia sotis\b/giu, 'sotumas toks trumpas'],
  [/\bnorimo energijos\b/giu, 'norimos energijos'],
  [/\bduos ilgalaikį sotumą(?!\p{L})/giu, 'suteiks ilgalaikį sotumą'],
  [/\btampa ramesnė ir maistingesnės\b/giu, 'tampa ramesnė ir sotesnė'],
  [/Prieš tai jautiesi išsekęs nuo nuolatinio spėliojimų, dabar\.?/giu, 'Anksčiau jauteisi išsekęs nuo nuolatinio spėliojimo.'],
  [/\bnuolatinio spėliojimų(?!\p{L})/giu, 'nuolatinio spėliojimo'],
  [/\bjaustis pilnam\s*\/\s*ai energijos\b/giu, 'turėti energijos'],
  [/\bpilnam\s*\/\s*ai\b/giu, 'pilnam'],
  [/\bvisus likusius darbo metus\b/giu, 'visą likusią darbo dieną'],
  [/\bsumažėjusia produktyvumu\b/giu, 'sumažėjusiu produktyvumu'],
  [/\bdidesnę produktyvumo dozę(?!\p{L})/giu, 'daugiau energijos'],
  [/\bproduktyvumo dozę(?!\p{L})/giu, 'daugiau energijos'],
  // Posts 87–91 batch — grammar, hook questions, filler patterns
  [/\bjauti mieguistumas ir tingulys\b/giu, 'jauti mieguistumą ir tingulį'],
  [/\bjauti mieguistumą ir tingulys\b/giu, 'jauti mieguistumą ir tingulį'],
  [/\bjauči mieguistum\w*/giu, 'jauti mieguistumą'],
  [/\bDažnai jauči mieguistum\w*/giu, 'Dažnai jauti mieguistumą'],
  [/\bturi aiškų\s+(\p{L}+)\s+planas\b/giu, 'turi aiškų $1 planą'],
  [/\btampa stresas\b/giu, 'tampa stresinga'],
  [/\bsu begalės užduočių/giu, 'su begale užduočių'],
  [/\bnėra pats taupumas\?\s*$/giu, 'nėra pats taupumas.'],
  [/\bsavitvirtybe\b/giu, 'pasitikėjimu'],
  [/\bDažnas net nežino\b/giu, 'Dažnai nežinai'],
  [/([Ss]upranti[^.!?]*po valgio)\./giu, '$1?'],
  [/([Tt]u nori[^.!?]*artimaisiais)\./giu, '$1?'],
  [/([Gg]albūt[^.!?]*diskomfort)\./giu, '$1?'],
  // Posts 92–96 batch
  [/\bsusivildavimas\b/giu, 'susivėlavimu'],
  [/\blaiko susivildavimas\b/giu, 'laiko susivėlavimui'],
  [/\blaiko improvizacija\b/giu, 'laiko improvizacijai'],
  [/\bneturi laiko improvizacija\b/giu, 'neturi laiko improvizacijai'],
  [/Štai kodėl dažnai/giu, 'Todėl dažnai'],
  [/\bŠtai kodėl\s+(?!neverta\b|reikia\b|svarbu\b|geriau\b|padės\b)([a-ząčęėįšųūž]+)\b/giu, 'Todėl $1'],
  [/\bSupratusi savo\b/giu, 'Supratęs savo'],
  [/^Mažiau emocinio$/giu, 'Mažiau emocinio valgymo'],
  [/^Mažiau paslėptų$/giu, 'Mažiau paslėptų kalorijų'],
  [/\bpriimti įvykius\b/giu, 'priimti sprendimus'],
  [/\bPriešingos situacijos atveju\b/giu, 'Tokiais atvejais'],
  [/\bmažiau traukia užkandžiauti\b/giu, 'mažiau norisi užkandžiauti'],
  [/\bDabar žinai, kad mažiau sprendimų\.\s*$/giu, 'Dabar žinai: mažiau sprendimų reiškia daugiau energijos kasdieniam gyvenimui.'],
  [/\bPraktiška struktūra\b/giu, 'Aiškus planas'],
  [/\bKasdien renkiesi ramiau\b/giu, 'Kasdienius sprendimus priimi ramiau'],
  [/\bIlgainiui tai pastebi kasdienybėje\b/giu, 'Ilgainiui pajusi skirtumą kasdienybėje'],
  [/\bpasijauti tarsi ne savo kūne\b/giu, 'atsiduri situacijose, kurioms sunku rasti paaiškinimą'],
  [/\bDažnai atsiranda situacijų, kurioms neturi aiškaus paaiškinimo\b/giu, 'Dažnai atsiduri situacijose, kurioms neturi aiškaus paaiškinimo'],
  [/\bpasikartodami kasdieninį režimą\b/giu, 'kartodamiesi kasdienėje rutinoje'],
  [/\bTuomet netgi gali nejausti, kodėl esi tokioje situacijoje\b/giu, 'Todėl gali net nepastebėti, kaip atsidūrei tokioje situacijoje'],
  [/\bleidžia iš anksto pasiruošti kitai dienai\b/giu, 'padeda iš anksto pasiruošti dienai'],
  [/\bdieną išlaikanti veikla\b/giu, 'kasdienė rutina'],
  [/\bneveda tavęs į tikslus\b/giu, 'nepadeda siekti tavo tikslų'],
  [/\bGalbūt nežinai, kurioje vietoje esi\b/giu, 'Galbūt nežinai, nuo ko pradėti'],
  [/\bnebesiblaškai priimdamas kiekvieną sprendimą\b/giu, 'nebesiblaškai dėl kiekvieno sprendimo'],
  [/\bpadeda išlaikyti ramybę\b/giu, 'padeda išlikti ramiau'],
  [/\bar visada žini\b/giu, 'ar visada žinai'],
  [/\bvisada žini\b/giu, 'visada žinai'],
  [/\bpasirinksiesi\b/giu, 'pasirinksi'],
  [/\bimpulsinės pirkimo\b/giu, 'impulsyvaus pirkimo'],
  [/\bruošti maisto\b/giu, 'ruošti maistą'],
  [/(?<!\p{L})ką pasikeitė(?!\p{L})/giu, 'kas pasikeitė'],
  [/\bnuolatinio spėliojimų\b/giu, 'nuolatinio spėliojimo'],
  [/\bSupratusi,\s+kad tikslas\.?\s*$/giu, 'Supranti, kad tikslas aiškus.'],
  [/\bMaisto skoniu gali būti paveiktas\b/giu, 'Netinkamu maisto pasirinkimu gali būti paveiktas'],
  [/\bprisijungi prie maisto pasirinkimo\b/giu, 'nesąmoningai renkiesi maistą, kuris'],
  [/\bnedrįsta kristi\b/giu, 'nemažėja'],
  [/\bsvoris vis tiek nedrįsta\b/giu, 'svoris vis tiek nemažėja'],
  [/\bsukurti tinkančių receptų\b/giu, 'sukurti tinkančius receptus'],
  [/\bįtūkstamas\b/giu, 'varginantis'],
  [/\bpadės tau įsitikinti\.\s*$/giu, 'padės tau įsitikinti, kad planas veikia.'],
  [/\bkauptuvės\b/giu, 'kaupiasi'],
  [/\bgrįžta kontrolė savo dienoje\b/giu, 'atgauni kontrolę savo dienoje'],
  [/\bpadeda kasdien maistą rinktis ramiau\b/giu, 'padeda kasdien ramiai rinktis maistą'],
  [/\bPlanuodamas\b/giu, 'Kai planuoji'],
  [/\bDažnas susiduria\b/giu, 'Daugelis susiduria'],
  [/(?<!\p{L})įsitvirtina stabiliai(?!\p{L})/giu, 'įsitvirtina'],
  [/\btrūksta aiškių žingsnių, ką daryti\b/giu, 'trūksta aiškumo, ką daryti'],
  [/\bPopietė be kritimo:/giu, 'Popietė be energijos kritimo:'],
  [/\bsukelia streso ir paskatino\b/giu, 'sukelia stresą ir paskatina'],
  [/\bsukelia streso\b/giu, 'sukelia stresą'],
  [/\bruošiant maistą\.\s*namuose\b/giu, 'ruošiant maistą namuose'],
  [/\bsukelia diskomforto\b/giu, 'sukelia diskomfortą'],
  [/\bdažnoje virtuvėje\b/giu, 'dažnai virtuvėje'],
  // Seen in Kalėdų Kampelis audit logs (2026-09/10)
  [/(?<!\p{L})jauti\s+(kaip|tarsi|lyg)(?!\p{L})/giu, 'jautiesi $1'],
  [/(?<!\p{L})kiekvienus\s+metus(?!\p{L})/giu, 'kiekvienais metais'],
  [/(?<!\p{L})jauti\s+begalin(?:is|į)\s+stres(?:as|ą)(?!\p{L})/giu, 'jauti didžiulį stresą'],
  [/(?<!\p{L})kojoj(?!\p{L})/giu, 'kojoms'],
  [/(?<!\p{L})ne\s+(mėgsta|mėgsti|žinai|žino|nori|gali|turi|reikia|patinka)(?!\p{L})/giu, 'ne$1'],
  [/(?<!\p{L})iki\s+kol(?!\p{L})/giu, 'kol'],
  [/(?<!\p{L})jauties(?!\p{L})/giu, 'jautiesi'],
  [/(?<!\p{L})jauti\s+stresas(?!\p{L})/giu, 'jauti stresą'],
  [/(?<!\p{L})jauti\s+nerimas(?!\p{L})/giu, 'jauti nerimą'],
  [/(?<!\p{L})jauti\s+spaudimas(?!\p{L})/giu, 'jauti spaudimą'],
  [/(?<!\p{L})jauti\s+nuovargis(?!\p{L})/giu, 'jauti nuovargį'],
  [/(^|[.!?…]\s+)Tris\s+poros(?!\p{L})/gmu, '$1Trys poros'],
  [/(?<!\p{L})padaryk\s+(jiems|jai|jam|jam|sau)\s+šventinę\s+nuotaiką/giu, 'sukurk $1 šventinę nuotaiką'],
  [/(?<!\p{L})kalėdos\s+artos(?!\p{L})/giu, 'Kalėdos arti'],
  [/(?<!\p{L})noro\s+pataikauti(?!\p{L})/giu, 'noro įtikti'],
  [/(?<!\p{L})(\p{L}{4,})\s?\(-?(?:a|i|ė|usi|ės|os)\)/giu, '$1'],
  // Audit batch30 (2026-10) — naturalness repairs (reference §13 / §22), not normative rules
  [/(?<!\p{L})parodyti\s+savo\s+dėmesį(?!\p{L})/giu, 'parodyti dėmesio'],
  [/(?<!\p{L})(?:kartais\s+)?tai\s+išleidžia\s+daugiau(?!\p{L})/giu, 'taip dažnai išleidi daugiau'],
  [/(?<!\p{L})pasirinkimas\s+visoms\s+šalims(?!\p{L})/giu, 'pasirinkimas abiem'],
  [/(?<!\p{L})jaukumo\s+ir\s+šviesaus\s+komforto(?!\p{L})/giu, 'jaukumo ir šilumos'],
  [/(?<!\p{L})filmų\s+vakaro\s+mėgėj/giu, 'filmų vakarų mėgėj'],
]
